### ISSUE TITLE
Creative Crafter Lags Entire Refined Storage Network

### ISSUE THREAD

**Issue by jmdev91** [starforcraft/Creative-Crafter#1]
While playing All The Mods 6 - To the Sky, I decided to give these a go. Placed five of them, only to find that my system slowed to a crawl. It was taking ages for my importers to pull items out of machines, the machines themselves (namely fully upgraded Mekanism ones) slowed down dramatically, and even my elevators took multiple seconds to register. When I finally realized these were their own mod, I took them out; wasn't until the last one was removed that my system returned to normal speeds.

**Comment by starforcraft** [comment]
I will soon make a performance Update but currently I don't have much time.

**Comment by necauqua** [comment]
Well it lags not just the network, but the server itself, tanking the TPS to the ground and resulting in all the lag you perceived.

It happens only when using in processing mode (with machines) because Refined Storage was not expecting a crafter that has a speed of 60k(!!!).

Nonetheless, this is technically a Refined Storage bug and should be fixed by https://github.com/refinedmods/refinedstorage/pull/3001, which would hopefully be in version 1.9.13

**Comment by starforcraft** [comment]
Yeah because the Creative Crafter is was too fast for the machines so the machines give TPS issues
